### PR TITLE
fix

### PR DESCRIPTION
**Pull request by ivukotic**
bypassed bytes was wrong. There is a padding of 4 bytes...

### CODE REVIEW

**Comment by brianhlin** [comment]
Could you reword your commit message to be more descriptive? Something like:

> Bypassed bytes should have a padding of 4 bytes

To help our future selves :)

**Comment by ivukotic** [comment]
not sure how to fix commit comment now, anyhow this is a bit longer explanation:
There was a bug in how binary formatted cinfo file content gets unpacked in python reporter. This affected only v3 of the cinfo files. 
Bug made for a way too large bytes_bypassed values. Cause of the bug was failure to notice a padding of 4 bytes inserted by C code.

**Comment by brianhlin** [comment]
[git rebase](https://scottmw.com/600/reword-commit-message-git/) is what you're looking for but the merge makes that tricky so we can just skip it for now. Are you running this version on your caches?

**Comment by ivukotic** [comment]
Hi,

Ok. Yes, this is what I am running everywhere.

Cheers,
Ilija

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Review by brianhlin — APPROVED** [review]

**Pull request merged**
