### PR TITLE
install gperftools-libs and use tcmalloc (software-4166)

### PR DESCRIPTION
**Pull request by ddavila0**

### CODE REVIEW

**Comment by brianhlin** [comment]
@ddavila0 we should install this in the base XCache image and set the env var for all the caches

**Comment by ddavila0** [comment]
@brianhlin , I've moved the install to the xcache image and added the LD_PRELOAD to the rest of the images

**Comment by brianhlin** [comment]
Could you squash the accidental addition of the `run` dir and typos? Also it looks like if you install `gperftools-dev` it'll give you the unversioned `.so`

**Comment by edquist** [comment]
I guess this works as long as the libtcmalloc version stays at .so.4

I also don't know the rules for `environment` here, but assuming it's supposed to be comma-separated it looks right.

PS Does it work?

**Comment by ddavila0** [comment]
@brianhlin I've done the squash, changed the package to install for gperftools-devel and change the library name to libtcmalloc.so.0
@edquist , yes Environment it's a comma separated list and yes, it works otherwise I won't be seeing libtmalloc in the pmap output.

**Comment by edquist** [comment]
>libtcmalloc.so.0
I think you mean `libtcmalloc.so` (the unversioned .so, which for now should be a symlink to .so.4)

**Pull request merged**
