### PR TITLE
Disable Travis (SOFTWARE-4252)

### PR DESCRIPTION
**Pull request by brianhlin**
Since we've got GHA working https://github.com/opensciencegrid/docker-xcache/actions

### CODE REVIEW

**Comment by matyasselmeci** [comment]
I don't see an action going for this PR. Does the action only trigger after the merge?

**Comment by brianhlin** [comment]
Correct, we only have the builds in GHA. We could set up another workflow for PR tests and can add that here

**Comment by matyasselmeci** [comment]
Let's do that before removing travis -- we should see code working before it gets merged into master.

**Comment by brianhlin** [comment]
As expected, the `pull_request` action failed because it doesn't have access to the secrets that we use for the intermediate builds (https://github.com/opensciencegrid/docker-xcache/runs/1386832693. I've switched it over to `pull_request_target` which will use the target branch's action instead so that it can safely access the secrets (https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks). Since there aren't any existing GHA on master, nothing will run for this particular PR.

Note that subsequent PRs will then create intermediate images in our GitHub repository (https://github.com/orgs/opensciencegrid/packages?repo_name=docker-xcache). It's not ideal but the actions will have to be reworked to use GHA artifacts or caches to pass off built images between jobs, which will take a fair amount of work.

**Review by matyasselmeci — APPROVED** [review]
LGTM.

**Comment by brianhlin** [comment]
Overriding CI since this PR disables Travis and GHA won't run for this particular PR, per above :crossed_fingers:

**Pull request merged**
