### PR TITLE
Cleaning the -k option

### PR DESCRIPTION
**Pull request by efajardo**

### CODE REVIEW

**Review by brianhlin — APPROVED** [review]
LGTM

**Review by brianhlin — CHANGES_REQUESTED** [review]
Actually, can you update the default number of log rotations to 10 so we don't change behavior?

**Review by brianhlin — APPROVED** [review]
LGTM

**Comment by efajardo** [comment]
@brianhlin does this trigger a build of `upcoming-fresh` cause I am testing it right now and I am seeing the old.

**Comment by brianhlin** [comment]
Yup and it looks like the GHA CI was successful for the `upcoming-fresh` push: https://github.com/opensciencegrid/docker-xcache/runs/1103092781?check_suite_focus=true. And I see the image here: https://hub.docker.com/layers/opensciencegrid/stash-cache/upcoming-fresh/images/sha256-73f2100a9616dc09c872c0a9d6e8e96a6f815ba8a8bb7a7e43d61de88f3108b7?context=explore

Strangely the Travis tests failed (https://travis-ci.com/github/opensciencegrid/docker-xcache) but the GHA tests were fine.

**Comment by efajardo** [comment]
There is something fishy:

This is the digest I am running:

```
    Image:          opensciencegrid/cms-xcache:upcoming-fresh
    Image ID:       docker-pullable://opensciencegrid/cms-xcache@sha256:655048418131cc827ce657097f1227141698cf29fc4e7438fc80bfd8a83a5b09
```

And this how supervisor.d looks like:

```
[root@esnet-xcache-01 xrootd]# cat /etc/supervisord.d/10-cms-xcache.conf 
[program:cms-xcache]
command=xrootd -c /etc/xrootd/xrootd-cms-xcache.cfg -k fifo -n cms-xcache -k 10 -s /var/run/xrootd/xrootd-cms-xcache.pid -l /var/log/xrootd/xrootd.log
user=xrootd
autorestart=true

[program:cms-xcache-cmsd]
command=/usr/bin/cmsd -c /etc/xrootd/xrootd-cms-xcache.cfg -k fifo -n cms-xcache -k 10 -s /var/run/xrootd/cmsd-cms-xcache.pid -l /var/log/xrootd/cmsd.log -I v4
user=xrootd
autorestart=true
```

**Comment by brianhlin** [comment]
Looks ok to me?

```
blin@blin-latitude:~$ podman images --digests | grep cms-xcache
docker.io/opensciencegrid/cms-xcache      upcoming-fresh  sha256:655048418131cc827ce657097f1227141698cf29fc4e7438fc80bfd8a83a5b09  4ec9c7ab1e78  2 hours ago    855 MB
localhost/opensciencegrid/cms-xcache      fresh           sha256:ba8eb7fad40bbd25fbc7b21ad4612f19363a68b376f2e1e9c97e26cf84d93ef7  db263d2f183e  8 weeks ago    539 MB
localhost/opensciencegrid/cms-xcache      upcoming-fresh  sha256:ba8eb7fad40bbd25fbc7b21ad4612f19363a68b376f2e1e9c97e26cf84d93ef7  db263d2f183e  8 weeks ago    539 MB

blin@blin-latitude:~$ podman run --rm -it opensciencegrid/cms-xcache:upcoming-fresh cat /etc/supervisord.d/10-cms-xcache.conf
[program:cms-xcache]
command=xrootd -c /etc/xrootd/xrootd-cms-xcache.cfg -k fifo -n cms-xcache -k %(ENV_XC_NUM_LOGROTATE)s -s /var/run/xrootd/xrootd-cms-xcache.pid -l /var/log/xrootd/xrootd.log
user=xrootd
autorestart=true
environment=LD_PRELOAD=/usr/lib64/libtcmalloc.so,TCMALLOC_RELEASE_RATE=10

[program:cms-xcache-cmsd]
command=/usr/bin/cmsd -c /etc/xrootd/xrootd-cms-xcache.cfg -k fifo -n cms-xcache -k %(ENV_XC_NUM_LOGROTATE)s -s /var/run/xrootd/cmsd-cms-xcache.pid -l /var/log/xrootd/cmsd.log
user=xrootd
autorestart=true
environment=LD_PRELOAD=/usr/lib64/libtcmalloc.so,TCMALLOC_RELEASE_RATE=10
```

**Pull request merged**
