### PR TITLE
Disable asyncio as a temporary workaround for an XRootD 5.3.0 bug (SOFTWARE-4716)

### PR DESCRIPTION
**Pull request by brianhlin**
https://github.com/xrootd/xrootd/commit/6a3da29f3c3f3e86df15e567f550187e5aab4ed6

### CODE REVIEW

**Comment by matyasselmeci** [comment]
Can you make sure this change gets reverted when we have 5.3.1 (or a patched 5.3.0)?

**Comment by brianhlin** [comment]
https://opensciencegrid.atlassian.net/browse/SOFTWARE-4715

**Review by djw8605 — APPROVED** [review]
Sure, looks good.

**Comment by brianhlin** [comment]
We don't care about the `fresh` GHA passing for the CI. Merging

**Pull request merged**
