### PR TITLE
making it executable

### PR DESCRIPTION
**Pull request by ivukotic**
forgot to do it yesterday

### CODE REVIEW

**Comment by brianhlin** [comment]
FWIW, it looks like `reporter.py` and `update-cric-status.sh` may need the same treatment

**Comment by ivukotic** [comment]
Added.
Thanks
ilija

**Comment by brianhlin** [comment]
CI failures unrelated to PR (https://opensciencegrid.atlassian.net/browse/SOFTWARE-3562?focusedCommentId=359209), merging

**Comment by brianhlin** [comment]
Argh, @djw8605 the test failures above prevent us from pushing new XCache images. @ivukotic while we sort out these issues, please carry `chmod` fixes in your own images.

**Pull request merged**
