### PR TITLE
Avoid clearing caches using their own rootdirs (SOFTWARE-4159)

### PR DESCRIPTION
**Pull request by brianhlin**

### CODE REVIEW

**Comment by efajardo** [comment]
Hold on so `XC_ROOTDIR` is not supposed to be just `/xcache`

**Comment by brianhlin** [comment]
Nope, it's `/xcache/namespace` to support the multi and single disk use cases and allow transition from single -> multi-disk. In the single disk mode, we still tell people to mount their host partition to `/xcache` so it'll create the namespace, meta, and data dirs for them.

**Comment by efajardo** [comment]
This PR is no longer requested but documentation should be udpated or the Dockerfile update to by default `XC_ROOTDIR` should be `/xcache`

**Comment by brianhlin** [comment]
@efajardo we can't change `XC_ROOTDIR` to `/xcache` because its current setting of `/xcache/namespace` allows us to support cases of a single disk mounted to `/xcache` with automatic creation of `/xcache/namespace`, `/xcache/meta1`, and `/xcache/data1` so that users can easily transition to a multi-disk setup where they have separate partitions for the namespace and X number of meta/data dirs.

**Comment by efajardo** [comment]
How does this affect @ivukotic stuff that expects it in `/xcache-meta/namespace`

**Comment by brianhlin** [comment]
IIRC, @ivukotic was already setting `oss.localroot /xcache/namespace`. I don't recall where he's been putting his data/meta dirs but as long as he mounts them as `/xcache/meta*` and `/xcache/data*` in the config, he should be fine. He can even mount them in any other location as long as he specifies the `oss.space` directives to look for them in the proper location.

**Review by efajardo — APPROVED** [review]
Since we are all ready using this in production this should be good.

**Pull request merged**
